DROP TABLE IF EXISTS COIN;

CREATE TABLE COIN(
    CURRENCY VARCHAR(255) PRIMARY KEY,
    RATE REAL,
    CURRENCY_CHINESE VARCHAR(10),
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP
                 );